# This file was generated by GoReleaser. DO NOT EDIT.
class Default < Formula
  desc "Your ultimate connection proxy."
  homepage "https://github.com/bokysan/socketace"
  version "1.0.9"
  bottle :unneeded

  if OS.mac?
    url "http://github.mycompany.com/bokysan/socketace-brew/releases/v1.0.9/socketace_1.0.9_darwin_amd64.tar.gz"
    sha256 "c7a665fd23dff28b86e71b387ec6a92807f455ef0c0ef45aab6799ab84edd0b7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.mycompany.com/bokysan/socketace-brew/releases/v1.0.9/socketace_1.0.9_linux_amd64.tar.gz"
      sha256 "249a402f2f0acd5b5e46a4324a0c3dcc477f9089a9dfb11ecf6af2471a3557d2"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "http://github.mycompany.com/bokysan/socketace-brew/releases/v1.0.9/socketace_1.0.9_linux_arm64.tar.gz"
        sha256 "146afc12ad68e52b908eafc06690b5384c3dcb75df2d6a9774113f953f99fec6"
      else
        url "http://github.mycompany.com/bokysan/socketace-brew/releases/v1.0.9/socketace_1.0.9_linux_armv6.tar.gz"
        sha256 "da8f5e11a2c3d0e303df5207753a35bef0b4b1ad2312c1eb108ee0283a270bb0"
      end
    end
  end
  
  head "https://github.com/bokysan/socketace.git"

  def install
    bin.install "socketace"
  end

  test do
    system "#{bin}/socketace version"
  end
end
