# This file was generated by GoReleaser. DO NOT EDIT.
class Default < Formula
  desc "Your ultimate connection proxy."
  homepage "https://github.com/bokysan/socketace"
  version "1.0.10"
  bottle :unneeded

  if OS.mac?
    url "http://github.mycompany.com/bokysan/socketace-brew/releases/v1.0.10/socketace_1.0.10_darwin_amd64.tar.gz"
    sha256 "b46ac6842d2482a6ebdd09304b84c35e30335674a40444979e54f798fed3e45e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.mycompany.com/bokysan/socketace-brew/releases/v1.0.10/socketace_1.0.10_linux_amd64.tar.gz"
      sha256 "9beb27338d3e944b030a88c6b49baa3ad6cb0abdd388f60ce10bb66302c5566a"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "http://github.mycompany.com/bokysan/socketace-brew/releases/v1.0.10/socketace_1.0.10_linux_arm64.tar.gz"
        sha256 "293ffcfe8303bad66693c098b9ac3901ce7e47f33c8d2a3d88ca2192b597082d"
      else
        url "http://github.mycompany.com/bokysan/socketace-brew/releases/v1.0.10/socketace_1.0.10_linux_armv6.tar.gz"
        sha256 "e80af869158d2703866bf1647fef55fe67d0b83d8c3bbb0f9b63141ba9689e88"
      end
    end
  end
  
  head "https://github.com/bokysan/socketace.git"

  def install
    bin.install "socketace"
  end

  test do
    system "#{bin}/socketace version"
  end
end
